### ISSUE TITLE
Bug: Can't install it - Bad addon structure

### ISSUE THREAD

**Issue by burekas7** [pustovitDmytro/areace#3]
Hi, @pustovitDmytro 

I'm getting an error while trying to install the addon.
It says that it has bad addon structure, something like that.

* By the way, can I use this addon to any channel that I have in Telegram or only te known sports channels?

areace-1.0.3
Kodi 20.1

Thanks.

**Comment by pustovitDmytro** [comment]
Hi, I'll look into this issue. 
You can try the archive I used before adding it to the official repository: [areace-1.0.3.zip](https://github.com/pustovitDmytro/areace/releases/download/v1.0.3/areace-1.0.3.zip) (or try version 1.0.4).

The addon uses a Telegram bot to receive information, so it needs to be added to a channel and have access to messages. If you are not an admin of the channel, I recommend creating your own channel and manually pasting the links there.

Regarding the Kodi version, I have Kodi 20.3. While I'm not sure if it's crucial, I'll take it into account during the investigation.

Also, please check the updated README.

**Comment by pustovitDmytro** [comment]
Update:
I have checked the installation of version 1.0.3 (both from the Kodi repository and GitHub releases), and it is working fine. The same goes for version 1.0.4, which is currently only available in GitHub releases.

I am using Kodi 20.3 and do not support versions that are not the latest, but I am not certain if this is crucial. Please attempt to reinstall the addon from the archive. If it doesn't work, it may be something device-specific. 

I am closing the issue for now; feel free to comment if there are any updates.

**Comment by burekas7** [comment]
@pustovitDmytro 

Oh I found why. I'm using Windows OS.

In the `addon.xml` you limits the addon only for `android`:
`<platform>android</platform>`

I changed it to:
`<platform>all</platform>`

And now it's installed.
So please update the `addon.xml`
